[package]
name = "dsc-commands-remover"
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["Alexiy Rybin <alexiy.rybin@gmail.com>"]
repository = "https://github.com/tapris-bot/dsc-commands-remover/"
description = "CLI tool to unregister all slash commands for a discord bot"
keywords = ["terminal", "cli"]
categories = ["command-line-utilities"]
license = "MIT"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dialoguer = "0.10"
poise = "0.5"
tokio = { version = "1", features = ["full"] }
